### PR TITLE
action.yml: upgrade NodeJS usage from v12 to v16

### PR DESCRIPTION
**Pull request by troley**
Ref. semestry/tasks#204

## Proposed changes

See title

## Testing

N/A

## Documentation

N/A

### CODE REVIEW

**Comment by johanwortel** [comment]
After several days of trying my conclusion is that we should stop using this action. The makers of Spectral have created a Github Action themselves. That can be used instead: https://github.com/stoplightio/spectral-action.

Problems with oas3-lint:
- The current action does not produce any results.
- The current action uses a bundle, but this bundle has not been updated for years. Actually the current implementation (i.e. the sources) is not suited for running from JavaScript at all.
- With some minor changes the action can be rewritten. (https://docs.stoplight.io/docs/spectral/eb68e7afd463e-spectral-in-java-script). That has been done in this PR.
- Due to an error in `@stoplight/spectral-ruleset-bundler` bundling is not possible. I have "resolved" this by manually changing its package.json file (see below).
- Even with the fixed bundle it does not work. Some sort of runtime module loading (module `@stoplight/spectral-rulesets`) is not recognized by WebPack, so we cannot run without the node_modules structure (or maybe part of it). 
- In workflow runs we usually install packages at runtime, but not in GitHub actions, there we need already installed packages, either in a node_modules structure or in a bundle. In this case working with node_modules would be the way to go.

Looking whether I missed something I found Spectral's own Github action. I sounds logical to use that. 

`Error in @stoplight/spectral-ruleset-bundler:`
The package (.json) uses so called conditional exports. That means that the actual form of the package depends on some external condition, in our case the fact that we are running from Node. A switch like structure is used and the specification demands that the "default" case, if present, is the last one in the list. Here it isn't. Node itself tolerates this, but WebPack and therefore `@vercel/ncc` (the loader recommended by GitHub), which uses WebPack, do not. Changing the order of the cases resolves this. If we would really use this package a fork might be a neater solution.

**Comment by MikeN123** [comment]
Wasn't this originally  @marcokrikke's thing? Maybe he has some input on it.

**Comment by marcokrikke** [comment]
It was done by Erik. But happy for the linter to be replaced by the Spectral action.

**Comment by MikeN123** [comment]
So @johanwortel I guess the idea is that we use the spectral thing? Possibly by forking the repo, so we don't get hacked if their repo gets hacked, nto sure with what permissions it runs :p

**Comment by MikeN123** [comment]
We've moved to spectral and can close this one, as confirmed by Johan.

**Pull request closed without merging**
